create new post
gustavofoa/dicasdepython.com.br pull request #30
Opened 2021-11-30 01:51 UTC by mcstol

2021-11-30 19:03 UTC, gustavofoa requested changes

2021-11-30 19:03 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +## Então agora vamos ler o arquivo que acabamos de criar
Sugestão: Como ler o arquivo CSV que acabamos de criar

2021-11-30 19:03 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Vamos abri o arquivo assim como fizemos no código anterior,  porem com uma pequena mudança o parâmetro que usamos anteriormente era 'w', porem agora vamos usar o 'r' de read, ou se preferir não preci
Vamos abrir...
...então temos o seguinte.

2021-11-30 19:03 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +![Arquivo aberto editor de planilhas](../images/como-criar-um-arquivo-csv-no-python/arquivo-aberto-editor-planilhas.png "Arquivo aberto no editor de planilhas"){:width=100%}
Sugestão: não termine o post com uma imagem.

Se não tiver nada mais na cabeça pra escrever, o que acha de escrever algo assim:

E aí, o que achou deste post? Gostou de aprender a trabalhar com arquivos CSVs no python?
Deixe aí nos comentários se este post foi útil pra você!

2021-12-03 03:11 UTC, gustavofoa requested changes

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Até o momento com os passos anteriores já atingimos nosso objetivo, mas ainda podemos melhorar um pouco mais.
mas ainda podemos melhorar um pouco mais. -> mas sempre podemos melhorar o nosso código. Certo?

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Vamos analizar alguns detalhes do código escrito, quando escrevemos os dados no arquivo CSV, nós criamos o objeto escritor, passamos para ele a variável
escrito, quando -> escrito. Quando

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Vamos analizar alguns detalhes do código escrito, quando escrevemos os dados no arquivo CSV, nós criamos o objeto escritor, passamos para ele a variável
objeto escritor -> objeto "escritor"

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +que aponta para o arquivo, configuramos o delimitador e depois escrevemos os dados. Dessa forma:
Dessa forma: -> Tudo junto desta forma:

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Notamos que em cada linha repetimos `csv.writer(csvfile, delimiter=',')`, isso faz que em cada linha estamos criando este objeto, para 3 linhas de dados pode não fazer diferença,
isso faz que -> isso faz com que

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Dessa forma um arquivo irá criar centenas ou milhares de objetos, isso irá consumir recursos de processamento, que se traduz em gastos, se criarmos algumas dezenas de arquivos por dia, porque não por
objetos. Isso

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Pensando nisso vamos utilizar um recurso do python e atribuir esse objeto a uma variável, dessa forma nós criamos esse objeto apenas uma vez e depois vamos apenas utilizar o mesmo objeto.
Pensando nisso vamos utilizar um recurso do python e atribuir esse objeto a uma variável -> Pensando nisso, ao invés de executar a função que cria o objeto `escritor` milhares de vezes, vamos executar esta função apenas uma vez e armazenar em uma variável (chamada `writer`, por exemplo) o objeto que ela retorna.

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Seguindo essa linha de pensamento, também podemos melhorar nosso cógigo de escrita, passando o objeto de escrita que está sendo criado a cada iteração do loop `for` para uma variável e apenas usar no
***Pode tirar esta parte, pq não otimiza utilização de recurso...***

2021-12-03 03:11 UTC, gustavofoa commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Pronto! Agora temos nosso código otimimizado para criar arquivos CSVs e consumir menos recursos!
e consumir menos recursos de memória e processamento!

2021-12-05 19:34 UTC, mcstol commented on content/posts/2021-11-29-como-criar-um-arquivo-csv-no-python.md
> +Seguindo essa linha de pensamento, também podemos melhorar nosso cógigo de escrita, passando o objeto de escrita que está sendo criado a cada iteração do loop `for` para uma variável e apenas usar no
Não entendi. Essa parte não fala de otimização de utilização de recurso mas sim de seguir a ideia de refatoração da escrita na leitura.

2021-12-09 10:17 UTC, gustavofoa approved these changes

2021-12-09 10:17 UTC, merged